name: build

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1
      - name: Install Updates
        run: |        
          sudo apt update
          sudo apt purge firefox -y
          sudo apt upgrade

      - name: Install packages
        run: |
          sudo apt -y install wget python3
          
      - name: Setup Toolchains
        run: |          
          bash init_clang_12.sh
          
      - name: Run build
        run: |
          export PATH=$PWD/toolchain/proton-clang/bin:$PATH
          bash auto_workflow_clang.sh

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: N_kernel_Proton-Clang_12
          path: AIK/N_KERNEL.*_PROTON_CLANG_12_LATEST.zip
