name: build

on:

  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - device: m21
          - device: m31
          - ksu_status: ksu
          - ksu_status: ""
    name: "ðŸš§ Build for ${{matrix.device}}"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          
      - name: Setup Toolchains
        run: |
          sudo apt update
          sudo apt install bison flex libssl-dev libarchive-tools -y
          mkdir -p toolchain
          cd toolchain
          echo 'Download antman and sync'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S
          echo 'Patch for glibc'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") --patch=glibc
          echo 'Done'
          
      - name: Run build
        run: |
          
          DEVICE=${{matrix.device}} ${{matrix.ksu_status}} ./build.sh

      - name: Device Name & Config
        run: |
          cat .config | grep CONFIG_LOCALVERSION=
          echo ''
          echo ''
          echo ''
          cat .config

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: AIK/N_KERNEL*.zip
          message: "Build COmpleted"

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: N_kernel-${{matrix.device}}_${{matrix.ksu_status}}_Clang_18
          path: AIK/N_KERNEL.*.zip
